"""
공유 유틸리티 모듈

프로젝트 전체에서 사용하는 상수, 경로, 유틸리티.
"""

from .constants import (
    MAX_OLLAMA_REASONING,
    MAX_TEXT_DRAFT_DISPLAY,
    MAX_TEXT_LLM_CONTEXT,
    MAX_TEXT_STORAGE,
    RATE_LIMIT_CLAUDE_PER_MINUTE,
    RATE_LIMIT_OLLAMA_PER_MINUTE,
    RATE_LIMIT_PIPELINE_PER_MINUTE,
)
from .paths import (
    CONFIG_DIR,
    DATA_DIR,
    DRAFTS_DIR,
    GATEWAY_DB,
    INTELLIGENCE_DB,
    PROJECT_ROOT,
    PROMPTS_DIR,
)

__all__ = [
    "MAX_TEXT_STORAGE",
    "MAX_TEXT_LLM_CONTEXT",
    "MAX_TEXT_DRAFT_DISPLAY",
    "MAX_OLLAMA_REASONING",
    "RATE_LIMIT_PIPELINE_PER_MINUTE",
    "RATE_LIMIT_CLAUDE_PER_MINUTE",
    "RATE_LIMIT_OLLAMA_PER_MINUTE",
    "PROJECT_ROOT",
    "CONFIG_DIR",
    "DATA_DIR",
    "GATEWAY_DB",
    "INTELLIGENCE_DB",
    "DRAFTS_DIR",
    "PROMPTS_DIR",
]
